version: '3.8'

services:
  mongodb-data1:
    container_name: mongodb-example1
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: projects
    volumes:
      - "mongo-data1:/data/db"
    networks:
      - network_example
  mongodb-data2:
    container_name: mongodb-example2
    image: mongo:latest
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: projects
    volumes:
      - type: volume
        source: mongo-data2
        target: "/data/db"
        read_only: false
    networks:
      - network_example

networks:
  network_example:
    name: network_example
    driver: bridge

volumes:
  mongo-data1:
    name: mongo-data1
  mongo-data2:
    name: mongo-data2
