version: '3.8'

services:
  nginx-example1:
    container_name: nginx-example1
    image: nginx:latest
    ports:
      - protocol: tcp
        published: 8080
        target: 80

  nginx-example2:
    container_name: nginx-example2
    image: nginx:latest
    ports:
      - "8081:80"