version: '3.8'

services:
  mongodb-example:
    container_name: mongodb-example
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: projects
    networks:
      - network_example

  mongodb-express-example:
    container_name: mongodb-express-example
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    networks:
      - network_example
    depends_on:
      - mongodb-example

networks:
  network_example:
    name: network_example
    driver: bridge
